name: CICD-API-PIPELINE-EB
env: 
  EB_PACKAGE_S3_BUCKET_NAME: "github-actions-s3-artem"
  EB_APPLICATION_NAME: "MY-API"
  EB_ENVIRONMENT_NAME: "MY-API-env"
  DEPLOY_PACKAGE_NAME: my_go_api_${{ github.sha }}.zip
  AWS_REGION_NAME: "us-east-1"
on:
  push:
    branches: 
      - main
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone
      uses: actions/checkout@v1

    - name: Create ZIP deployment package 
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}

    - name: Copy Deployment package to S3 bucket
      run: aws-s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
    - name: Happy message
      run: echo "CI Pipeline part finished"
